### ISSUE TITLE
Aspect ratio

### ISSUE THREAD

**Issue by kurtextrem** [Skwuruhl/siegeads#1]
As I totally suck in math and coming from https://www.reddit.com/r/Rainbow6TTS/comments/e72e3t/change_scope_sensitivities_to_use_focal_length_as/, do the equations factor in aspect ratio or rather, is aspect ratio relevant for the calculations?

**Comment by Skwuruhl** [comment]
Rainbow 6 uses vertical FOV which means it's consistent no matter the aspect ratio.

If rainbow 6 didn't use vertical FOV then yes, it would be relevant.

**Comment by kurtextrem** [comment]
Thanks!
